version: "3.10"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - .:/app
    restart: unless-stopped
    container_name: app_sahilll
    ports:
      - 8000:8000
    # command: uvicorn --host=0.0.0.0 app.main:app --port=8000
    command: uvicorn app.main:app --host=0.0.0.0 --port=8000
    networks:
      example-network:
        ipv4_address: 172.16.238.10

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus_sahil
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      example-network:
        ipv4_address: 172.16.238.11

  grafana:
    image: grafana/grafana
    container_name: grafana_sahil
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - ./grafana/config.monitoring
    networks:
      example-network:
        ipv4_address: 172.16.238.12

networks:
  example-network:
    name: example-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
