global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ['localhost:9090']
      # - targets: ['localhost:9092']
  - job_name: 'app'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:8000']
      # - targets: ['app:8000', 'app_1:8000', 'app_2:8000']

